# docker compose for cpp dev env

version: "3.8"
services:
  cpp_dev_container:
    container_name: cpp_dev_container
    build: .
    environment:
      - TORCHLIBS=/home/libtorch
      - ENTR_INOTIFY_WORKAROUND=1
      - DISPLAY=host.docker.internal:0
    volumes:
      - /Users/Andy/Code/PyCppInterOpRL/:/home/Cpp
      - /Users/Andy/.config/nvim:/root/.config/nvim
      - /tmp/.X11-unix:/tmp/.X11-unix


    command: ["tail", "-f", "/dev/null"]
